// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANgUYgVaGqwQ8p990ypvwuCxMNabj9mGQ',
    appId: '1:366980632437:web:76cde67f43020381864d3c',
    messagingSenderId: '366980632437',
    projectId: 'project2-stocktrackerapp',
    authDomain: 'project2-stocktrackerapp.firebaseapp.com',
    storageBucket: 'project2-stocktrackerapp.firebasestorage.app',
    measurementId: 'G-TQCJ3E59W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUoEcHDKNIVzrQ27vnJsbDmTwPtnkT_YQ',
    appId: '1:366980632437:android:c947f579c0b19331864d3c',
    messagingSenderId: '366980632437',
    projectId: 'project2-stocktrackerapp',
    storageBucket: 'project2-stocktrackerapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX7i90h8yXrenH8XMwHXyqxiBA-J6cxxA',
    appId: '1:366980632437:ios:5962de4f73cbf87a864d3c',
    messagingSenderId: '366980632437',
    projectId: 'project2-stocktrackerapp',
    storageBucket: 'project2-stocktrackerapp.firebasestorage.app',
    iosBundleId: 'com.example.proj2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX7i90h8yXrenH8XMwHXyqxiBA-J6cxxA',
    appId: '1:366980632437:ios:5962de4f73cbf87a864d3c',
    messagingSenderId: '366980632437',
    projectId: 'project2-stocktrackerapp',
    storageBucket: 'project2-stocktrackerapp.firebasestorage.app',
    iosBundleId: 'com.example.proj2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANgUYgVaGqwQ8p990ypvwuCxMNabj9mGQ',
    appId: '1:366980632437:web:d9ce848fcddaeb4a864d3c',
    messagingSenderId: '366980632437',
    projectId: 'project2-stocktrackerapp',
    authDomain: 'project2-stocktrackerapp.firebaseapp.com',
    storageBucket: 'project2-stocktrackerapp.firebasestorage.app',
    measurementId: 'G-SB9LQNK2T9',
  );
}
